org: ce7clc
app: clc-serverless-hello-app

stages:
  dev:
    observability: true
service: lcchua-aws-node-http-api-project
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
#  profile: serverless

functions:
  hello:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

# Insert raw CloudFormation (resources, outputs…) in the deployed template
resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: lcchua-usersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-offline
